FROM ubuntu:18.04

COPY . .
RUN mkdir -p workspace/src
RUN mv config.sh workspace
RUN mv Makefile workspace/src

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1
ENV INSTALL_HPP_DIR=/opt/openrobots
ENV DEVEL_HPP_DIR=/workspace
ENV CMAKE_PREFIX_PATH=/opt/openrobots:/opt/ros/melodic

RUN apt-get update -y && apt-get install -y \
   curl \
   gnupg2 \
   && rm -rf /var/lib/apt/lists/*

RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list
RUN apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN echo "deb [arch=amd64] http://robotpkg.openrobots.org/wip/packages/debian/pub bionic robotpkg" > /etc/apt/sources.list.d/robotpkg.list
RUN echo "deb [arch=amd64] http://robotpkg.openrobots.org/wip/packages/debian/pub bionic robotpkg" > /etc/apt/sources.list.d/robotpkg.list
RUN echo "deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub bionic robotpkg" >> /etc/apt/sources.list.d/robotpkg.list
RUN curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | apt-key add -

RUN apt update -y && apt install -y libgraphviz-dev robotpkg-py36-hpp-manipulation-corba robotpkg-py36-qt5-hpp-gepetto-viewer robotpkg-py36-qt5-hpp-gui robotpkg-py36-qt5-hpp-plot robotpkg-py36-hpp-environments robotpkg-py36-hpp-tutorial+doc robotpkg-ompl ros-melodic-pr2-description python3-numpy ros-melodic-catkin emacs git tigervnc-standalone-server tigervnc-xorg-extension terminator xfce4 \
robotpkg-py36-hpp-baxter robotpkg-py36-hpp-romeo robotpkg-py36-hpp-universal-robot


# for midori web browser
RUN apt install -y libwebkit2gtk-4.0-37 libjavascriptcoregtk-4.0-18 libgcr-ui-3-1 libgck-1-0 libpeas-1.0-0 libxml2-utils gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-libav
RUN dpkg -i midori_9.0.0-1_amd64.deb
RUN rm -f midori_9.0.0-1_amd64.deb
