FROM flamiraux/hpp-4.10-2

RUN apt install -qqy mesa-utils \
    net-tools \
    novnc \
    x11-apps

COPY . .
#CMD ["midori", "index.html"]

RUN mkdir ~/.vnc \
 && echo "#!/bin/sh\nstartxfce4" > ~/.vnc/xstartup \
 && chmod +x ~/.vnc/xstartup

ADD entrypoint.sh /
CMD /entrypoint.sh

#ENV DISPLAY=:0
#ENV QT_X11_NO_MITSHM=1
